export { PiAcpAgent, type PiAcpAgentOptions } from "./acp/agent.ts";
export { PiAcpSession, type ClientFeatures, type SessionOpenOptions } from "./acp/session.ts";
export { SessionProjection, type SessionUpdate, assistantStopReasonToAcp } from "./acp/translate.ts";
export { buildReplay, type ReplayResult } from "./acp/history.ts";
export { convertPrompt, UnsupportedPromptContentError, type ConvertedPrompt } from "./acp/prompt.ts";
export { classifyToolCall, type ToolCallFacts } from "./acp/tool-facts.ts";
export { buildConfigOptions, findModel, modelValue } from "./acp/config-options.ts";
export { BUILTIN_COMMANDS, availableCommandsFor, parseSlashCommand } from "./acp/commands.ts";
export { buildAuthMethods, TERMINAL_AUTH_METHOD_ID } from "./acp/auth.ts";
export { serve, stdioStream, type ServerHandle } from "./server.ts";
export { resolveSettings, SettingsError, HELP_TEXT, type Settings } from "./settings.ts";
export { VERSION, PACKAGE_NAME } from "./version.ts";
